package org.cc.wos;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by crco0001 on 8/31/2016.
 */
public class WosHelperFunctions {

    public static final HashMap<String,String> SUBJECT_TO_MACRO9 = new HashMap<String, String>()
    {
        {

            put("agriculture, dairy & animal science", "Biologi");
            put("agriculture, multidisciplinary", "Biologi");
            put("agronomy", "Biologi");
            put("biodiversity conservation", "Biologi");
            put("biology", "Biologi");
            put("developmental biology", "Biologi");
            put("ecology", "Biologi");
            put("entomology", "Biologi");
            put("evolutionary biology", "Biologi");
            put("fisheries", "Biologi");
            put("forestry", "Biologi");
            put("horticulture", "Biologi");
            put("limnology", "Biologi");
            put("marine & freshwater biology", "Biologi");
            put("mycology", "Biologi");
            put("ornithology", "Biologi");
            put("plant sciences", "Biologi");
            put("reproductive biology", "Biologi");
            put("veterinary sciences", "Biologi");
            put("zoology", "Biologi");
            put("acoustics", "Fysik");
            put("astronomy & astrophysics", "Fysik");
            put("chemistry, physical", "Fysik");
            put("nuclear science & technology", "Fysik");
            put("optics", "Fysik");
            put("physics, applied", "Fysik");
            put("physics, atomic, molecular & chemical", "Fysik");
            put("physics, condensed matter", "Fysik");
            put("physics, fluids & plasmas", "Fysik");
            put("physics, mathematical", "Fysik");
            put("physics, multidisciplinary", "Fysik");
            put("physics, nuclear", "Fysik");
            put("physics, particles & fields", "Fysik");
            put("thermodynamics", "Fysik");
            put("environmental sciences", "Geovetenskap");
            put("geochemistry & geophysics", "Geovetenskap");
            put("geography, physical", "Geovetenskap");
            put("geology", "Geovetenskap");
            put("geosciences, multidisciplinary", "Geovetenskap");
            put("meteorology & atmospheric sciences", "Geovetenskap");
            put("mineralogy", "Geovetenskap");
            put("oceanography", "Geovetenskap");
            put("paleontology", "Geovetenskap");
            put("soil science", "Geovetenskap");
            put("water resources", "Geovetenskap");
            put("archaeology", "Humaniora");
            put("art", "Humaniora");
            put("classics", "Humaniora");
            put("cultural studies", "Humaniora");
            put("dance", "Humaniora");
            put("ethics", "Humaniora");
            put("film, radio, television", "Humaniora");
            put("folklore", "Humaniora");
            put("history", "Humaniora");
            put("history & philosophy of science", "Humaniora");
            put("history of social sciences", "Humaniora");
            put("humanities, multidisciplinary", "Humaniora");
            put("language & linguistics", "Humaniora");
            put("linguistics", "Humaniora");
            put("literary reviews", "Humaniora");
            put("literary theory & criticism", "Humaniora");
            put("literature", "Humaniora");
            put("literature, african, australian, canadian", "Humaniora");
            put("literature, american", "Humaniora");
            put("literature, british isles", "Humaniora");
            put("literature, german, dutch, scandinavian", "Humaniora");
            put("literature, romance", "Humaniora");
            put("literature, slavic", "Humaniora");
            put("medieval & renaissance studies", "Humaniora");
            put("music", "Humaniora");
            put("philosophy", "Humaniora");
            put("poetry", "Humaniora");
            put("religion", "Humaniora");
            put("theater", "Humaniora");
            put("chemistry, analytical", "Kemi");
            put("chemistry, applied", "Kemi");
            put("chemistry, inorganic & nuclear", "Kemi");
            put("chemistry, multidisciplinary", "Kemi");
            put("chemistry, organic", "Kemi");
            put("crystallography", "Kemi");
            put("electrochemistry", "Kemi");
            put("polymer science", "Kemi");
            put("spectroscopy", "Kemi");
            put("logic", "Matematik");
            put("mathematics", "Matematik");
            put("mathematics, applied", "Matematik");
            put("mathematics, interdisciplinary applications", "Matematik");
            put("statistics & probability", "Matematik");
            put("allergy", "Medicin");
            put("anatomy & morphology", "Medicin");
            put("andrology", "Medicin");
            put("anesthesiology", "Medicin");
            put("audiology & speech-language pathology", "Medicin");
            put("biochemical research methods", "Medicin");
            put("biochemistry & molecular biology", "Medicin");
            put("biophysics", "Medicin");
            put("biotechnology & applied microbiology", "Medicin");
            put("cardiac & cardiovascular systems", "Medicin");
            put("cell & tissue engineering", "Medicin");
            put("cell biology", "Medicin");
            put("chemistry, medicinal", "Medicin");
            put("clinical neurology", "Medicin");
            put("critical care medicine", "Medicin");
            put("cytology & histology", "Medicin");
            put("dentistry, oral surgery & medicine", "Medicin");
            put("dermatology", "Medicin");
            put("emergency medicine", "Medicin");
            put("endocrinology & metabolism", "Medicin");
            put("gastroenterology & hepatology", "Medicin");
            put("genetics & heredity", "Medicin");
            put("geriatrics & gerontology", "Medicin");
            put("gerontology", "Medicin");
            put("health care sciences & services", "Medicin");
            put("hematology", "Medicin");
            put("immunology", "Medicin");
            put("infectious diseases", "Medicin");
            put("integrative & complementary medicine", "Medicin");
            put("mathematical & computational biology", "Medicin");
            put("medical ethics", "Medicin");
            put("medical informatics", "Medicin");
            put("medical laboratory technology", "Medicin");
            put("medicine, general & internal", "Medicin");
            put("medicine, legal", "Medicin");
            put("medicine, research & experimental", "Medicin");
            put("microbiology", "Medicin");
            put("microscopy", "Medicin");
            put("multidisciplinary sciences", "Medicin");
            put("neuroimaging", "Medicin");
            put("neurosciences", "Medicin");
            put("nursing", "Medicin");
            put("nutrition & dietetics", "Medicin");
            put("obstetrics & gynecology", "Medicin");
            put("oncology", "Medicin");
            put("ophthalmology", "Medicin");
            put("orthopedics", "Medicin");
            put("otorhinolaryngology", "Medicin");
            put("parasitology", "Medicin");
            put("pathology", "Medicin");
            put("pediatrics", "Medicin");
            put("peripheral vascular disease", "Medicin");
            put("pharmacology & pharmacy", "Medicin");
            put("physiology", "Medicin");
            put("primary health care", "Medicin");
            put("psychiatry", "Medicin");
            put("psychology, clinical", "Medicin");
            put("public, environmental & occupational health", "Medicin");
            put("radiology, nuclear medicine & medical imaging", "Medicin");
            put("rehabilitation", "Medicin");
            put("respiratory system", "Medicin");
            put("rheumatology", "Medicin");
            put("sport sciences", "Medicin");
            put("substance abuse", "Medicin");
            put("surgery", "Medicin");
            put("toxicology", "Medicin");
            put("transplantation", "Medicin");
            put("tropical medicine", "Medicin");
            put("urology & nephrology", "Medicin");
            put("virology", "Medicin");
            put("agricultural economics & policy", "Samhällsvetenskap");
            put("anthropology", "Samhällsvetenskap");
            put("area studies", "Samhällsvetenskap");
            put("asian studies", "Samhällsvetenskap");
            put("behavioral sciences", "Samhällsvetenskap");
            put("business", "Samhällsvetenskap");
            put("business, finance", "Samhällsvetenskap");
            put("communication", "Samhällsvetenskap");
            put("criminology & penology", "Samhällsvetenskap");
            put("demography", "Samhällsvetenskap");
            put("economics", "Samhällsvetenskap");
            put("education & educational research", "Samhällsvetenskap");
            put("education, scientific disciplines", "Samhällsvetenskap");
            put("education, special", "Samhällsvetenskap");
            put("environmental studies", "Samhällsvetenskap");
            put("ethnic studies", "Samhällsvetenskap");
            put("family studies", "Samhällsvetenskap");
            put("geography", "Samhällsvetenskap");
            put("health policy & services", "Samhällsvetenskap");
            put("hospitality, leisure, sport & tourism", "Samhällsvetenskap");
            put("industrial relations & labor", "Samhällsvetenskap");
            put("information science & library science", "Samhällsvetenskap");
            put("international relations", "Samhällsvetenskap");
            put("law", "Samhällsvetenskap");
            put("management", "Samhällsvetenskap");
            put("planning & development", "Samhällsvetenskap");
            put("political science", "Samhällsvetenskap");
            put("psychology", "Samhällsvetenskap");
            put("psychology, applied", "Samhällsvetenskap");
            put("psychology, biological", "Samhällsvetenskap");
            put("psychology, developmental", "Samhällsvetenskap");
            put("psychology, educational", "Samhällsvetenskap");
            put("psychology, experimental", "Samhällsvetenskap");
            put("psychology, mathematical", "Samhällsvetenskap");
            put("psychology, multidisciplinary", "Samhällsvetenskap");
            put("psychology, psychoanalysis", "Samhällsvetenskap");
            put("psychology, social", "Samhällsvetenskap");
            put("public administration", "Samhällsvetenskap");
            put("social issues", "Samhällsvetenskap");
            put("social sciences, biomedical", "Samhällsvetenskap");
            put("social sciences, interdisciplinary", "Samhällsvetenskap");
            put("social sciences, mathematical methods", "Samhällsvetenskap");
            put("social work", "Samhällsvetenskap");
            put("sociology", "Samhällsvetenskap");
            put("urban studies", "Samhällsvetenskap");
            put("women's studies", "Samhällsvetenskap");
            put("agricultural engineering", "Teknik");
            put("architecture", "Teknik");
            put("automation & control systems", "Teknik");
            put("computer applications & cybernetics", "Teknik");
            put("computer critical reviews", "Teknik");
            put("computer science, artificial intelligence", "Teknik");
            put("computer science, cybernetics", "Teknik");
            put("computer science, hardware & architecture", "Teknik");
            put("computer science, information systems", "Teknik");
            put("computer science, interdisciplinary applications", "Teknik");
            put("computer science, software engineering", "Teknik");
            put("computer science, theory & methods", "Teknik");
            put("construction & building technology", "Teknik");
            put("energy & fuels", "Teknik");
            put("engineering, aerospace", "Teknik");
            put("engineering, biomedical", "Teknik");
            put("engineering, chemical", "Teknik");
            put("engineering, civil", "Teknik");
            put("engineering, electrical & electronic", "Teknik");
            put("engineering, environmental", "Teknik");
            put("engineering, geological", "Teknik");
            put("engineering, industrial", "Teknik");
            put("engineering, manufacturing", "Teknik");
            put("engineering, marine", "Teknik");
            put("engineering, mechanical", "Teknik");
            put("engineering, multidisciplinary", "Teknik");
            put("engineering, ocean", "Teknik");
            put("engineering, petroleum", "Teknik");
            put("ergonomics", "Teknik");
            put("food science & technology", "Teknik");
            put("imaging science & photographic technology", "Teknik");
            put("instruments & instrumentation", "Teknik");
            put("materials science, biomaterials", "Teknik");
            put("materials science, ceramics", "Teknik");
            put("materials science, characterization & testing", "Teknik");
            put("materials science, coatings & films", "Teknik");
            put("materials science, composites", "Teknik");
            put("materials science, multidisciplinary", "Teknik");
            put("materials science, paper & wood", "Teknik");
            put("materials science, textiles", "Teknik");
            put("mechanics", "Teknik");
            put("metallurgy & metallurgical engineering", "Teknik");
            put("mining & mineral processing", "Teknik");
            put("nanoscience & nanotechnology", "Teknik");
            put("operations research & management science", "Teknik");
            put("remote sensing", "Teknik");
            put("robotics", "Teknik");
            put("telecommunications", "Teknik");
            put("transportation", "Teknik");
            put("transportation science & technology", "Teknik");
            put("green & sustainable science & technology","Teknik"); // manually added, not in data from VR




        }
    };




}
